name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn ci

      - name: Run unit tests (jest)
        run: yarn run test
      
      - name: Run e2e tests (cypress)
        uses: cypress-io/github-action@v5
        with:
          build: yarn run build
          start: yarn run start
